---
services:
  palworld:
    image: crpi-5iuh3e1kl6fp7sjz.cn-beijing.personal.cr.aliyuncs.com/madnpc/palworld-server-docker:latest
    container_name: palworld-server
    restart: unless-stopped
    stop_grace_period: 30s  # Set to however long you are willing to wait for the container to gracefully stop
   
    ports:
      - 8211:8211/udp
      - 27015:27015/udp  # Required if you want your server to show up in the community servers tab
      - 8212:8212/tcp  # REST API enabled port, enabled by default. DO NOT PORT FORWARD THIS.
    
    env_file:
      - .env

    volumes:
      - ./palworld:/palworld/
